### ISSUE TITLE
Post gets cut off if "<" or ">" are in the sent post

### ISSUE THREAD

**Issue by psbj** [cellsheet/chlib#35]
As the title says, you are unable to send "<" or ">" in a post.

The post is sent through, but anything after the "<" or ">" is cut off.

For example:

`group.sendPost("Syntax: setcmd <command> <response>")` will only send "Syntax: setcmd " as a message.

Edit: Did some testing and it seems this can be fixed by removing the `if not html:` on line 215 (and thus removing a tab on line 216)

**Comment by LordYusei** [comment]
If you go into your RecvPost definition and add:
if self.user == user: return
                                                if post.post[0] == ".":   ##Here is the Prefix part
                                                                                  data = post.post[1:].split(" ", 1)
                                                                                  if len(data) > 1:
                                                                                                        cmd, args = data[0], data[1]
                                                                                  else:
                                                                                                        cmd, args = data[0], ""
You can use a command like in ch.py but without having to worry about the setcmd part. That's how I figured it out easier. Plus, it means you can do:
if cmd == "say" and len(args) > 0:
            group.sendPost(args)

Hope I help you at all in figuring it out. :)

**Comment by LordYusei** [comment]
If you would like to test it out feel free to use my chlib base bot located in http://justarandomplaceyo.chatango.com

**Comment by psbj** [comment]
I already do that. I don't think you understand the issue.

Have your bot do this:

`group.sendPost("this part will get sent<and this part won\'t")`

Then you will see what the issue is.

**Comment by LordYusei** [comment]
Yeah I see what you mean. I missed that totally during my coding. More than likely the reason it is not sending is because when you use the > symbol it expects it to be the end of a html code as in: <b>This is bolded text</b>. For some reason with my version of chlib it doesn't send anything with what you had. Once I changed it to say <b></b> It sends perfectly fine. What you could try is when you send the command encase it in Apostrophes which as far as I know is how the commands are done.

**Comment by Hazerdous** [comment]
This is due to the way chatango parses HTML in messages. In reality, it's only a problem with bots and custom clients because the default clients escape html in messages before sending them. By default, ch.py does this as well, but it is easy to disable allowing you to send html in messages.

This feature is disabled by default in chlib.py, if you want to enable it, causing all posts to (by default) escape html, you can change `html=True` to `html=False` in the `group.sendPost` definition on line 213
This will cause all messages to escape html by default, thus `<font>`, `<br>`, `<b>`, etc. will not work, and will show the html code in the message itself, but also `<something>`, `<3`, `<Post post>` will show, which would be the desired result.

If you expect a commands output to often contain < or > that are not html, you can disable html for an individual message by sending `html=False` as an argument to the `group.sendPost` function, this will effectively convert all `<` and `>` to `&lt;` and `&gt;` respectively, which appear in posts as `<` and `>`, but do not parse their content as html. Example:
`group.sendPost("This is a <Post post>", html=False)`


Also, the reason removing `if not html:` on line 215 fixes this, is that you are forcing the following line (which normally only occurs if you tell the function to not use html, hence "if not html:") to escape the html. If you always want the html to be escaped, this "works", but is not the proper method, the proper way would be to, again, change `html=True` to `html=False` in line 213, which would allow you to force html to work by sending `html=True` as an argument to the `group.sendPost` function.

**Comment by piks** [comment]
Seems nothing needs to be done here, closing
